# Generated by Django 2.1.7 on 2019-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_num1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_num2',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='hr_manger',
            name='contact_num1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='hr_manger',
            name='contact_num2',
            field=models.CharField(max_length=12),
        ),
    ]
