# Generated by Django 2.1.7 on 2019-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190424_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='previous_organization_experience',
            field=models.CharField(max_length=50),
        ),
    ]
