# Generated by Django 2.2 on 2019-05-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('closing_date', models.DateField()),
                ('attached_file', models.FileField(default='no-file.file', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='document',
            field=models.FileField(default='no-file.file', upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='descriptions',
            field=models.CharField(max_length=100),
        ),
    ]
