# Generated by Django 2.1.7 on 2019-05-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_degree_department_field_institute_internshipexperience_internshipreference_internshipresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_acknowledged', models.CharField(max_length=2)),
                ('started_at', models.DateTimeField()),
                ('interview_question_candidate_answer', models.PositiveIntegerField()),
                ('job_status', models.CharField(max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Applicant')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='accounts.Internship')),
                ('interview_question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.InterviewQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_acknowledged', models.CharField(max_length=2)),
                ('started_at', models.DateTimeField()),
                ('interview_question_candidate_answer', models.PositiveIntegerField()),
                ('job_status', models.CharField(max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Applicant')),
                ('interview_question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.InterviewQuestion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employer', models.CharField(max_length=20)),
                ('current_designation', models.CharField(max_length=20)),
                ('current_organization_experience', models.CharField(max_length=10)),
                ('objective', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('skills', models.CharField(max_length=20)),
                ('min_salary', models.PositiveIntegerField()),
                ('extra_curricular', models.CharField(max_length=50)),
                ('other_interests', models.CharField(max_length=50)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Applicant')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='accounts.Internship')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employer', models.CharField(max_length=20)),
                ('current_designation', models.CharField(max_length=20)),
                ('current_organization_experience', models.CharField(max_length=10)),
                ('objective', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('skills', models.CharField(max_length=20)),
                ('min_salary', models.PositiveIntegerField()),
                ('extra_curricular', models.CharField(max_length=50)),
                ('other_interests', models.CharField(max_length=50)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Job')),
            ],
        ),
    ]
