# Generated by Django 2.2 on 2019-04-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offices_Name', models.CharField(max_length=30)),
                ('HRManager', models.CharField(max_length=30)),
            ],
        ),
    ]
